
apiVersion: v1
kind: Service
metadata:
  name: imagen-tarjeta-api-service
spec:
  selector:
    app: imagen-tarjeta-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP # Cambia a ClusterIP si solo es interno / LoadBalancer


